
MOV DX, OFFSET HOLA
MOV AH, 09H
INT 21H  
MOV DX,OFFSET salto
INT 21H


LEERA:          
    MOV DX, OFFSET VAR_A
    MOV AH, 09H  
    INT 21H  
    MOV DX,OFFSET salto
    INT 21H
    
    MOV AH,01H 
    
    INT 21H   ;LEE UN ASCII Y LO GUARDA EN AL
       
CMP AL,30H
JL LEERA
CMP AL,39H
JG LEERA  
SUB AL,30H
MOV A,AL                  
;** DE PREFERECNIA A>B, SINO RESTA==FF



MOV DX,OFFSET salto
MOV AH,09h
INT 21h

    
LEERB:    
    MOV DX, OFFSET VAR_B
    MOV AH, 09H  
    INT 21H  
    MOV DX,OFFSET salto
    INT 21H
    
    MOV AH, 01H
    INT 21H
    MOV AH, 00H
CMP AL,30H
JL LEERB
CMP AL,39H
JG LEERB
SUB AL,30H  
MOV B,AL      ;ALMACENAR EL VALOR B
      
      ;OPERACIONES
MOV BL,A
ADD AL,BL
MOV SUMA,AL ;SUMA        

MOV AL,B 
MUL BL                ;MULTIPLACION
MOV MULTIPLICACION, AL             

;RESTA CON SIGNO    
MOV AL,B       
CMP AL,BL
JG  RESTAA
JL  RESTAB       
RESTAA:
    SUB AL,BL ; RESTA B-A
    MOV RESTA, AL
    MOV SIGNO, 2DH
    JMP DIVICION
RESTAB:
    SUB BL,AL ; RESTA A-B
    MOV RESTA, BL

DIVICION:
MOV AL,A
MOV BL, B
DIV BL    ;A/B
MOV COCIENTE, AL
MOV RESIDUO, AH   

       ;RESULTADOS 
       ;SUMA                  
MOV DX,OFFSET salto
MOV AH,09h
INT 21h
MOV DX, OFFSET MSJ_SUMA
MOV AH, 09H  
INT 21H
       ;PRIMER DIGITO
MOV AL,SUMA
SHR AL, 4 
CMP AL, 09H
JG HA
ADD AL, 30H
JMP IMPRIMIR_S

HA:     
    ADD AL, 37H
    
IMPRIMIR_S:
MOV DL, AL
MOV AH, 02H  
INT 21H    
      ;SEGUNDO DIGITO
MOV AL,SUMA
AND AL, 0FH 
CMP AL, 09H
JG HA2
ADD AL, 30H
JMP IMPRIMIR_S2

HA2:     
    ADD AL, 37H
    
IMPRIMIR_S2:
MOV DL, AL
MOV AH, 02H  
INT 21H  
    ;RESTA                  
MOV DX,OFFSET salto
MOV AH,09h
INT 21h
MOV DX, OFFSET MSJ_RESTA
MOV AH, 09H  
INT 21H
        ;SIGNO
MOV AH, 02  
MOV DL, SIGNO
INT 21H
       ;PRIMER DIGITO
MOV AL,RESTA
SHR AL, 4 
CMP AL, 09H
JG HA_R
ADD AL, 30H
JMP IMPRIMIR_R

HA_R:     
    ADD AL, 37H
    
IMPRIMIR_R:
MOV DL, AL
MOV AH, 02H  
INT 21H    
      ;SEGUNDO DIGITO
MOV AL,RESTA
AND AL, 0FH 
CMP AL, 09H
JG HA2_R
ADD AL, 30H
JMP IMPRIMIR_R2

HA2_R:     
    ADD AL, 37H
    
IMPRIMIR_R2:
MOV DL, AL
MOV AH, 02H  
INT 21H
    ;PRODUCTO                  
MOV DX,OFFSET salto
MOV AH,09h
INT 21h
MOV DX, OFFSET MSJ_MULTI
MOV AH, 09H  
INT 21H
       ;PRIMER DIGITO
MOV AL,MULTIPLICACION
SHR AL, 4 
CMP AL, 09H
JG HA_M
ADD AL, 30H
JMP IMPRIMIR_M

HA_M:     
    ADD AL, 37H
    
IMPRIMIR_M:
MOV DL, AL
MOV AH, 02H  
INT 21H    
      ;SEGUNDO DIGITO
MOV AL,MULTIPLICACION
AND AL, 0FH 
CMP AL, 09H
JG HA2_M
ADD AL, 30H
JMP IMPRIMIR_M2

HA2_M:     
    ADD AL, 37H
    
IMPRIMIR_M2:
MOV DL, AL
MOV AH, 02H  
INT 21H
    ;COCIENTE                  
MOV DX,OFFSET salto
MOV AH,09h
INT 21h
MOV DX, OFFSET MSJ_COCIENTE
MOV AH, 09H  
INT 21H
       ;PRIMER DIGITO
MOV AL,COCIENTE
SHR AL, 4 
CMP AL, 09H
JG HA_C
ADD AL, 30H
JMP IMPRIMIR_C

HA_C:     
    ADD AL, 37H
    
IMPRIMIR_C:
MOV DL, AL
MOV AH, 02H  
INT 21H    
      ;SEGUNDO DIGITO
MOV AL,COCIENTE
AND AL, 0FH 
CMP AL, 09H
JG HA2_C
ADD AL, 30H
JMP IMPRIMIR_C2

HA2_C:     
    ADD AL, 37H
    
IMPRIMIR_C2:
MOV DL, AL
MOV AH, 02H  
INT 21H
      ;RESIDUP                  
MOV DX,OFFSET salto
MOV AH,09h
INT 21h
MOV DX, OFFSET MSJ_RESIDUO
MOV AH, 09H  
INT 21H
       ;PRIMER DIGITO
MOV AL,RESIDUO
SHR AL, 4 
CMP AL, 09H
JG HA_RES
ADD AL, 30H
JMP IMPRIMIR_RES

HA_RES:     
    ADD AL, 37H
    
IMPRIMIR_RES:
MOV DL, AL
MOV AH, 02H  
INT 21H    
      ;SEGUNDO DIGITO
MOV AL,RESIDUO
AND AL, 0FH 
CMP AL, 09H
JG HA2_RES
ADD AL, 30H
JMP IMPRIMIR_RES2

HA2_RES:     
    ADD AL, 37H
    
IMPRIMIR_RES2:
MOV DL, AL
MOV AH, 02H  
INT 21H




INT 20H  

;VARIABLES NUMERICAS
A DB 00H
B DB 00H
SUMA DB 00H  ;SI "SUMA DB OOH" la proxima "int 21h" NO se ejecuta  (?
RESTA DB 00H
MULTIPLICACION DB 00H   
COCIENTE DB 00H
RESIDUO DB 00H
SIGNO DB 00H    ; SIGNO DE LA RESTA

;VARIABLES MSJ
HOLA DB "BIENVENIDO, POR FAVOR INTRODUZCA LOS VALORES A TRABAJAR $"     
VAR_A DB "INTRODUZCA EL PRIMER NUMERO (No MAYOR)$"
SALTO DB 13,10,"$" ;SALTO DE LINEA                               
VAR_B DB "INTRODUZCA EL SEGUNDO NUMERO (No MENOR)$"
MSJ_SUMA DB "LA SUMA ES: $"
MSJ_RESTA DB "LA RESTA ES: $"
MSJ_MULTI DB "LA MULTIPLICACION ES: $"
MSJ_COCIENTE DB "EL COCIENTE DE LA DIVISION ES: $"
MSJ_RESIDUO DB "EL RESIUDO DE LA DIVISION ES: $"